import * as images from './images';

export const wallet = [
  { caption: '', src: images.wallet1 },
  { caption: '', src: images.wallet2 },
  { caption: '', src: images.wallet3 },
  { caption: '', src: images.wallet4 },
  { caption: '', src: images.wallet5 },
  { caption: '', src: images.wallet6 },
  { caption: '', src: images.wallet7 },
];

export const antenna = [
  { caption: '', src: images.antenna1 },
  { caption: '', src: images.antenna2 },
];

export const skyminer = [
  { caption: '', src: images.skyminer1 },
  { caption: '', src: images.skyminer2 },
  { caption: '', src: images.skyminer3 },
  { caption: '', src: images.skyminer4 },
  { caption: '', src: images.skyminer5 },
  { caption: '', src: images.skyminer6 },
  { caption: '', src: images.skyminer7 },
  { caption: '', src: images.skyminer8 },
  { caption: '', src: images.skyminer9 },
  { caption: '', src: images.skyminer10 },
  { caption: '', src: images.skyminer11 },
  { caption: '', src: images.skyminer12 },
  { caption: '', src: images.skyminer13 },
  { caption: '', src: images.skyminer14 },
];

export const diySkyminer = [
  { caption: '', src: images.diySkyminer1 },
  { caption: '', src: images.diySkyminer2 },
  { caption: '', src: images.diySkyminer3 },
  { caption: '', src: images.diySkyminer4 },
  { caption: '', src: images.diySkyminer5 },
  { caption: '', src: images.diySkyminer6 },
  { caption: '', src: images.diySkyminer7 },
  { caption: '', src: images.diySkyminer8 },
  { caption: '', src: images.diySkyminer9 },
  { caption: '', src: images.diySkyminer10 },
  { caption: '', src: images.diySkyminer11 },
  { caption: '', src: images.diySkyminer12 },
  { caption: '', src: images.diySkyminer13 },
  { caption: '', src: images.diySkyminer14 },
  { caption: '', src: images.diySkyminer15 },
  { caption: '', src: images.diySkyminer16 },
  { caption: '', src: images.diySkyminer17 },
  { caption: '', src: images.diySkyminer18 },
  { caption: '', src: images.diySkyminer19 },
  { caption: '', src: images.diySkyminer21 },
  { caption: '', src: images.diySkyminer22 },
  { caption: '', src: images.diySkyminer23 },
  { caption: '', src: images.diySkyminer24 },
  { caption: '', src: images.diySkyminer25 },
  { caption: '', src: images.diySkyminer26 },
  { caption: '', src: images.diySkyminer27 },
  { caption: '', src: images.diySkyminer28 },
  { caption: '', src: images.diySkyminer29 },
  { caption: '', src: images.diySkyminer31 },
  { caption: '', src: images.diySkyminer32 },
  { caption: '', src: images.diySkyminer33 },
  { caption: '', src: images.diySkyminer34 },
  { caption: '', src: images.diySkyminer35 },
  { caption: '', src: images.diySkyminer36 },
  { caption: '', src: images.diySkyminer37 },
  { caption: '', src: images.diySkyminer38 },
  { caption: '', src: images.diySkyminer39 },
  { caption: '', src: images.diySkyminer40 },
  { caption: '', src: images.diySkyminer41 },
  { caption: '', src: images.diySkyminer42 },
  { caption: '', src: images.diySkyminer43 },
  { caption: '', src: images.diySkyminer44 },
  { caption: '', src: images.diySkyminer45 },
  { caption: '', src: images.diySkyminer46 },
  { caption: '', src: images.diySkyminer47 },
  { caption: '', src: images.diySkyminer48 },
  { caption: '', src: images.diySkyminer49 },
  { caption: '', src: images.diySkyminer51 },
  { caption: '', src: images.diySkyminer52 },
];

