export const en = {
  title: 'Skycoin Team',
  description: 'Bios of the Skycoin team',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Synth',
        email: '',
        picture: 'synth.jpg',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Houwu is one of the creators behind Ethereum, and the author of the Obelisk whitepaper which sits at the heart of our decentralized Internet and currency. He was formerly a researcher at Tsinghua University.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: 'steve.jpg',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin West',
    bios: [
      {
        name: 'Bradford Stephens',
        email: 'bradford@skycoin.net',
        picture: 'bradford.jpg',
        title: 'Chief Operations Officer',
        bio: 'Bradford formerly served as a C-level executive at five VC-backed companies. He is the creator of Spire, one of the first distributed SQL databases. In addition to the Big Data field, Bradford also operated companies in fashion, security, and adtech. His teams also drove several exits, including one public M&A. Bradford holds a degree in Computer Science and Political Science, specializing in distributed systems.',
      },
      {
        name: 'Catherine Byerly',
        email: 'catherine@skycoin.net',
        picture: 'catherine.jpg',
        title: 'Associate Director of Marketing',
        bio: 'Catherine Byerly is a marketer with experience in the digital, traditional, and affiliate spaces. Before entering marketing, she worked as a journalist on projects which received awards from American City Business Journals and the Associated Press. Byerly holds degrees in Political Science and Communication.',
      },
      {
        name: 'Daken Freeborn',
        email: '',
        picture: 'daken.jpg',
        title: 'Events Director',
        bio: 'Daken Freeborn brings more than 20 years of events experience to Skycoin. He has previously worked with hospitality brands including MGM Resorts International, Hilton Worldwide, and Caesars Entertainment. An early investor in Skycoin, he is passionate about systems of distributed ledgers, open-sources cryptocurrency platforms, and free and decentralized internet possibilities.',
      },
      {
        name: 'Angela',
        email: '',
        picture: 'angela.jpg',
        title: 'Community Director',
        bio: 'Part of the crypto community since 2015, Angela has been an active voice in assisting and growing multiple crypto projects through Telegram, Discord, and Reddit communities.',
      },
    ],
  },
  east: {
    title: 'Skycoin East',
    bios: [
      {
        name: 'Sam',
        email: '',
        picture: 'sam.jpg',
        title: '',
        bio: 'In 2014, Sam began investing in blockchain and now holds a number of successful portfolios. He is currently a founding Partner of a management consulting firm with offices in Shanghai and Singapore. Prior to that, Sam served a Singapore group as Global Project Manager. He also served a Germany-based Fortune 500 company as Project Manager and Solution Architect. He holds a degree from UniSA.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: 'jesse.jpg',
        title: '',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. In 2014, Sun was COO to one of the first blockchain companies. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Mary Li',
        email: '',
        picture: 'mary.jpg',
        title: '',
        bio: 'Li is a serial entrepreneur who began blockchain angel investing in 2015. During her time in the blockchain industry, she has been responsible for marketing efforts at several blockchain startups. In 2017, Li founded a blockchain investment fund that focused on blockchain startups and digital currency.',
      },
      {
        name: 'Michael Weng',
        email: '',
        picture: '',
        title: '',
        bio: 'Michael has more than 10 years of experience in software development, software reverse engineering, and network attack and defense. He started coding in junior high school, at 13 years old. Michael would go on to work at two public companies and lead the development team of an IoT platform for home appliances.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: 'simon.jpg',
        title: 'Co-Founder of Gamification Giant Ltd.',
        bio: 'Hobbs has 28 years of high-level technical experience in delivering complex, high-volume IT projects on time and on budget. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Amaury Hernandez Aguila',
        email: '',
        picture: 'amaury.jpg',
        title: 'CX Developer',
        bio: 'Amaury Aguila is a computer systems engineer with an expertise in machine learning and data science. He holds a master’s degree in Computer Science, and is currently pursuing a doctoral degree in computer science.',
      },
      {
        name: 'Evan Lin',
        email: '',
        picture: 'evan.jpg',
        title: 'BBS and Kitty Cash developer',
        bio: 'Evan Lin is Skycoin’s main developer for Skycoin BBS. Lin left university to pursue a career in software development. His personal projects include; cross-platform applications written using the Qt framework with QML/ C++; APIs in Golang and Node.JS hosted on cloud services such as AWS and GCS; creation of an ROS package for maintaining linear movement via rotary encoders for dual-wheeled robots. Lin is passionate about open- source technology, cryptocurrency, decentralized applications, and linux.',
      },
      {
        name: 'Konstantin Ivanov',
        email: '',
        picture: 'konstantin.jpg',
        title: 'CXO Developer',
        bio: '',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Mike Doty',
        title: 'Co-Founder of Ark',
        picture: 'mike.jpg',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: 'michael.jpg',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners',
        picture: 'richard.jpg',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: 'john.jpg',
        bio: 'John Henry Clippinger is currently a research scientist at the MIT Media Lab’s Human Dynamics Group. He is also Co-Founder and Executive Director of ID3. Previously, Dr. Clippinger was Founder and Co-director of The Law Lab at Harvard University. He is also a member of the eG8 Forum and the Global Leadership Telco Council and the Risk Analysis Network for the World Economic Forum.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: 'patrick.jpg',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: 'josh.jpg',
        bio: 'Founder of three successful online marketing and advertising companies, Ogle grew each business from less than $50k in funding to six-figure profits profits within two years. Ogle specializes in lead generation and free or cheap ways to grow business, including unusual approaches to making products/services “go viral.” He is a Cornell University alumnus.',
      },
      {
        name: 'Andrew Masanto',
        title: 'Board Of Directors at Cornerstone Capital Inc. | Entrepreneur and Investor',
        picture: 'andrew.jpg',
        bio: 'Andrew Masanto currently runs a US investment Holding Company, Land Invest LLC, and is an active advisor to several specialty media buying companies. Previously, he founded www.altitudeshoes.com which became the UK’s leading seller of Men’s Height Increasing Shoes. After its sale, Masanto founded Higher Click SEO Agency (acquired in 2013). He has also lectured at Harvard Business School and Oxford University on the topic of digital marketing.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: 'alphabit.jpg',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: 'tokenkey.jpg',
        bio: 'TokenKey is an end-to-end solution for ICO and token launches.',
      },
    ],
  },
};

export const zh = {
  title: 'Skycoin Team',
  description: 'Bios of the Skycoin team',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Synth',
        email: '',
        picture: 'synth.jpg',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Houwu is one of the creators behind Ethereum, and the author of the Obelisk whitepaper which sits at the heart of our decentralized Internet and currency. He was formerly a researcher at Tsinghua University.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: 'steve.jpg',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin West',
    bios: [
      {
        name: 'Bradford Stephens',
        email: 'bradford@skycoin.net',
        picture: 'bradford.jpg',
        title: 'Chief Operations Officer',
        bio: 'Bradford formerly served as a C-level executive at five VC-backed companies. He is the creator of Spire, one of the first distributed SQL databases. In addition to the Big Data field, Bradford also operated companies in fashion, security, and adtech. His teams also drove several exits, including one public M&A. Bradford holds a degree in Computer Science and Political Science, specializing in distributed systems.',
      },
      {
        name: 'Catherine Byerly',
        email: 'catherine@skycoin.net',
        picture: 'catherine.jpg',
        title: 'Associate Director of Marketing',
        bio: 'Catherine Byerly is a marketer with experience in the digital, traditional, and affiliate spaces. Before entering marketing, she worked as a journalist on projects which received awards from American City Business Journals and the Associated Press. Byerly holds degrees in Political Science and Communication.',
      },
      {
        name: 'Daken Freeborn',
        email: '',
        picture: 'daken.jpg',
        title: 'Events Director',
        bio: 'Daken Freeborn brings more than 20 years of events experience to Skycoin. He has previously worked with hospitality brands including MGM Resorts International, Hilton Worldwide, and Caesars Entertainment. An early investor in Skycoin, he is passionate about systems of distributed ledgers, open-sources cryptocurrency platforms, and free and decentralized internet possibilities.',
      },
      {
        name: 'Angela',
        email: '',
        picture: 'angela.jpg',
        title: 'Community Director',
        bio: 'Part of the crypto community since 2015, Angela has been an active voice in assisting and growing multiple crypto projects through Telegram, Discord, and Reddit communities.',
      },
    ],
  },
  east: {
    title: 'Skycoin East',
    bios: [
      {
        name: 'Sam',
        email: '',
        picture: 'sam.jpg',
        title: '',
        bio: 'In 2014, Sam began investing in blockchain and now holds a number of successful portfolios. He is currently a founding Partner of a management consulting firm with offices in Shanghai and Singapore. Prior to that, Sam served a Singapore group as Global Project Manager. He also served a Germany-based Fortune 500 company as Project Manager and Solution Architect. He holds a degree from UniSA.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: 'jesse.jpg',
        title: '',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. In 2014, Sun was COO to one of the first blockchain companies. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Mary Li',
        email: '',
        picture: 'mary.jpg',
        title: '',
        bio: 'Li is a serial entrepreneur who began blockchain angel investing in 2015. During her time in the blockchain industry, she has been responsible for marketing efforts at several blockchain startups. In 2017, Li founded a blockchain investment fund that focused on blockchain startups and digital currency.',
      },
      {
        name: 'Michael Weng',
        email: '',
        picture: '',
        title: '',
        bio: 'Michael has more than 10 years of experience in software development, software reverse engineering, and network attack and defense. He started coding in junior high school, at 13 years old. Michael would go on to work at two public companies and lead the development team of an IoT platform for home appliances.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: 'simon.jpg',
        title: 'Co-Founder of Gamification Giant Ltd.',
        bio: 'Hobbs has 28 years of high-level technical experience in delivering complex, high-volume IT projects on time and on budget. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Amaury Hernandez Aguila',
        email: '',
        picture: 'amaury.jpg',
        title: 'CX Developer',
        bio: 'Amaury Aguila is a computer systems engineer with an expertise in machine learning and data science. He holds a master’s degree in Computer Science, and is currently pursuing a doctoral degree in computer science.',
      },
      {
        name: 'Evan Lin',
        email: '',
        picture: 'evan.jpg',
        title: 'BBS and Kitty Cash developer',
        bio: 'Evan Lin is Skycoin’s main developer for Skycoin BBS. Lin left university to pursue a career in software development. His personal projects include; cross-platform applications written using the Qt framework with QML/ C++; APIs in Golang and Node.JS hosted on cloud services such as AWS and GCS; creation of an ROS package for maintaining linear movement via rotary encoders for dual-wheeled robots. Lin is passionate about open- source technology, cryptocurrency, decentralized applications, and linux.',
      },
      {
        name: 'Konstantin Ivanov',
        email: '',
        picture: 'konstantin.jpg',
        title: 'CXO Developer',
        bio: '',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Mike Doty',
        title: 'Co-Founder of Ark',
        picture: 'mike.jpg',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: 'michael.jpg',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners',
        picture: 'richard.jpg',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: 'john.jpg',
        bio: 'John Henry Clippinger is currently a research scientist at the MIT Media Lab’s Human Dynamics Group. He is also Co-Founder and Executive Director of ID3. Previously, Dr. Clippinger was Founder and Co-director of The Law Lab at Harvard University. He is also a member of the eG8 Forum and the Global Leadership Telco Council and the Risk Analysis Network for the World Economic Forum.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: 'patrick.jpg',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: 'josh.jpg',
        bio: 'Founder of three successful online marketing and advertising companies, Ogle grew each business from less than $50k in funding to six-figure profits profits within two years. Ogle specializes in lead generation and free or cheap ways to grow business, including unusual approaches to making products/services “go viral.” He is a Cornell University alumnus.',
      },
      {
        name: 'Andrew Masanto',
        title: 'Board Of Directors at Cornerstone Capital Inc. | Entrepreneur and Investor',
        picture: 'andrew.jpg',
        bio: 'Andrew Masanto currently runs a US investment Holding Company, Land Invest LLC, and is an active advisor to several specialty media buying companies. Previously, he founded www.altitudeshoes.com which became the UK’s leading seller of Men’s Height Increasing Shoes. After its sale, Masanto founded Higher Click SEO Agency (acquired in 2013). He has also lectured at Harvard Business School and Oxford University on the topic of digital marketing.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: 'alphabit.jpg',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: 'tokenkey.jpg',
        bio: 'TokenKey is an end-to-end solution for ICO and token launches.',
      },
    ],
  },
};

export const ru = {
  title: 'Skycoin Team',
  description: 'Bios of the Skycoin team',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Synth',
        email: '',
        picture: 'synth.jpg',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Houwu is one of the creators behind Ethereum, and the author of the Obelisk whitepaper which sits at the heart of our decentralized Internet and currency. He was formerly a researcher at Tsinghua University.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: 'steve.jpg',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin West',
    bios: [
      {
        name: 'Bradford Stephens',
        email: 'bradford@skycoin.net',
        picture: 'bradford.jpg',
        title: 'Chief Operations Officer',
        bio: 'Bradford formerly served as a C-level executive at five VC-backed companies. He is the creator of Spire, one of the first distributed SQL databases. In addition to the Big Data field, Bradford also operated companies in fashion, security, and adtech. His teams also drove several exits, including one public M&A. Bradford holds a degree in Computer Science and Political Science, specializing in distributed systems.',
      },
      {
        name: 'Catherine Byerly',
        email: 'catherine@skycoin.net',
        picture: 'catherine.jpg',
        title: 'Associate Director of Marketing',
        bio: 'Catherine Byerly is a marketer with experience in the digital, traditional, and affiliate spaces. Before entering marketing, she worked as a journalist on projects which received awards from American City Business Journals and the Associated Press. Byerly holds degrees in Political Science and Communication.',
      },
      {
        name: 'Daken Freeborn',
        email: '',
        picture: 'daken.jpg',
        title: 'Events Director',
        bio: 'Daken Freeborn brings more than 20 years of events experience to Skycoin. He has previously worked with hospitality brands including MGM Resorts International, Hilton Worldwide, and Caesars Entertainment. An early investor in Skycoin, he is passionate about systems of distributed ledgers, open-sources cryptocurrency platforms, and free and decentralized internet possibilities.',
      },
      {
        name: 'Angela',
        email: '',
        picture: 'angela.jpg',
        title: 'Community Director',
        bio: 'Part of the crypto community since 2015, Angela has been an active voice in assisting and growing multiple crypto projects through Telegram, Discord, and Reddit communities.',
      },
    ],
  },
  east: {
    title: 'Skycoin East',
    bios: [
      {
        name: 'Sam',
        email: '',
        picture: 'sam.jpg',
        title: '',
        bio: 'In 2014, Sam began investing in blockchain and now holds a number of successful portfolios. He is currently a founding Partner of a management consulting firm with offices in Shanghai and Singapore. Prior to that, Sam served a Singapore group as Global Project Manager. He also served a Germany-based Fortune 500 company as Project Manager and Solution Architect. He holds a degree from UniSA.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: 'jesse.jpg',
        title: '',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. In 2014, Sun was COO to one of the first blockchain companies. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Mary Li',
        email: '',
        picture: 'mary.jpg',
        title: '',
        bio: 'Li is a serial entrepreneur who began blockchain angel investing in 2015. During her time in the blockchain industry, she has been responsible for marketing efforts at several blockchain startups. In 2017, Li founded a blockchain investment fund that focused on blockchain startups and digital currency.',
      },
      {
        name: 'Michael Weng',
        email: '',
        picture: '',
        title: '',
        bio: 'Michael has more than 10 years of experience in software development, software reverse engineering, and network attack and defense. He started coding in junior high school, at 13 years old. Michael would go on to work at two public companies and lead the development team of an IoT platform for home appliances.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: 'simon.jpg',
        title: 'Co-Founder of Gamification Giant Ltd.',
        bio: 'Hobbs has 28 years of high-level technical experience in delivering complex, high-volume IT projects on time and on budget. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Amaury Hernandez Aguila',
        email: '',
        picture: 'amaury.jpg',
        title: 'CX Developer',
        bio: 'Amaury Aguila is a computer systems engineer with an expertise in machine learning and data science. He holds a master’s degree in Computer Science, and is currently pursuing a doctoral degree in computer science.',
      },
      {
        name: 'Evan Lin',
        email: '',
        picture: 'evan.jpg',
        title: 'BBS and Kitty Cash developer',
        bio: 'Evan Lin is Skycoin’s main developer for Skycoin BBS. Lin left university to pursue a career in software development. His personal projects include; cross-platform applications written using the Qt framework with QML/ C++; APIs in Golang and Node.JS hosted on cloud services such as AWS and GCS; creation of an ROS package for maintaining linear movement via rotary encoders for dual-wheeled robots. Lin is passionate about open- source technology, cryptocurrency, decentralized applications, and linux.',
      },
      {
        name: 'Konstantin Ivanov',
        email: '',
        picture: 'konstantin.jpg',
        title: 'CXO Developer',
        bio: '',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Mike Doty',
        title: 'Co-Founder of Ark',
        picture: 'mike.jpg',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: 'michael.jpg',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners',
        picture: 'richard.jpg',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: 'john.jpg',
        bio: 'John Henry Clippinger is currently a research scientist at the MIT Media Lab’s Human Dynamics Group. He is also Co-Founder and Executive Director of ID3. Previously, Dr. Clippinger was Founder and Co-director of The Law Lab at Harvard University. He is also a member of the eG8 Forum and the Global Leadership Telco Council and the Risk Analysis Network for the World Economic Forum.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: 'patrick.jpg',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: 'josh.jpg',
        bio: 'Founder of three successful online marketing and advertising companies, Ogle grew each business from less than $50k in funding to six-figure profits profits within two years. Ogle specializes in lead generation and free or cheap ways to grow business, including unusual approaches to making products/services “go viral.” He is a Cornell University alumnus.',
      },
      {
        name: 'Andrew Masanto',
        title: 'Board Of Directors at Cornerstone Capital Inc. | Entrepreneur and Investor',
        picture: 'andrew.jpg',
        bio: 'Andrew Masanto currently runs a US investment Holding Company, Land Invest LLC, and is an active advisor to several specialty media buying companies. Previously, he founded www.altitudeshoes.com which became the UK’s leading seller of Men’s Height Increasing Shoes. After its sale, Masanto founded Higher Click SEO Agency (acquired in 2013). He has also lectured at Harvard Business School and Oxford University on the topic of digital marketing.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: 'alphabit.jpg',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: 'tokenkey.jpg',
        bio: 'TokenKey is an end-to-end solution for ICO and token launches.',
      },
    ],
  },
};

export const ko = {
  title: 'Skycoin Team',
  description: 'Bios of the Skycoin team',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Synth',
        email: '',
        picture: 'synth.jpg',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Houwu is one of the creators behind Ethereum, and the author of the Obelisk whitepaper which sits at the heart of our decentralized Internet and currency. He was formerly a researcher at Tsinghua University.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: 'steve.jpg',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin West',
    bios: [
      {
        name: 'Bradford Stephens',
        email: 'bradford@skycoin.net',
        picture: 'bradford.jpg',
        title: 'Chief Operations Officer',
        bio: 'Bradford formerly served as a C-level executive at five VC-backed companies. He is the creator of Spire, one of the first distributed SQL databases. In addition to the Big Data field, Bradford also operated companies in fashion, security, and adtech. His teams also drove several exits, including one public M&A. Bradford holds a degree in Computer Science and Political Science, specializing in distributed systems.',
      },
      {
        name: 'Catherine Byerly',
        email: 'catherine@skycoin.net',
        picture: 'catherine.jpg',
        title: 'Associate Director of Marketing',
        bio: 'Catherine Byerly is a marketer with experience in the digital, traditional, and affiliate spaces. Before entering marketing, she worked as a journalist on projects which received awards from American City Business Journals and the Associated Press. Byerly holds degrees in Political Science and Communication.',
      },
      {
        name: 'Daken Freeborn',
        email: '',
        picture: 'daken.jpg',
        title: 'Events Director',
        bio: 'Daken Freeborn brings more than 20 years of events experience to Skycoin. He has previously worked with hospitality brands including MGM Resorts International, Hilton Worldwide, and Caesars Entertainment. An early investor in Skycoin, he is passionate about systems of distributed ledgers, open-sources cryptocurrency platforms, and free and decentralized internet possibilities.',
      },
      {
        name: 'Angela',
        email: '',
        picture: 'angela.jpg',
        title: 'Community Director',
        bio: 'Part of the crypto community since 2015, Angela has been an active voice in assisting and growing multiple crypto projects through Telegram, Discord, and Reddit communities.',
      },
    ],
  },
  east: {
    title: 'Skycoin East',
    bios: [
      {
        name: 'Sam',
        email: '',
        picture: 'sam.jpg',
        title: '',
        bio: 'In 2014, Sam began investing in blockchain and now holds a number of successful portfolios. He is currently a founding Partner of a management consulting firm with offices in Shanghai and Singapore. Prior to that, Sam served a Singapore group as Global Project Manager. He also served a Germany-based Fortune 500 company as Project Manager and Solution Architect. He holds a degree from UniSA.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: 'jesse.jpg',
        title: '',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. In 2014, Sun was COO to one of the first blockchain companies. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Mary Li',
        email: '',
        picture: 'mary.jpg',
        title: '',
        bio: 'Li is a serial entrepreneur who began blockchain angel investing in 2015. During her time in the blockchain industry, she has been responsible for marketing efforts at several blockchain startups. In 2017, Li founded a blockchain investment fund that focused on blockchain startups and digital currency.',
      },
      {
        name: 'Michael Weng',
        email: '',
        picture: '',
        title: '',
        bio: 'Michael has more than 10 years of experience in software development, software reverse engineering, and network attack and defense. He started coding in junior high school, at 13 years old. Michael would go on to work at two public companies and lead the development team of an IoT platform for home appliances.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: 'simon.jpg',
        title: 'Co-Founder of Gamification Giant Ltd.',
        bio: 'Hobbs has 28 years of high-level technical experience in delivering complex, high-volume IT projects on time and on budget. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Amaury Hernandez Aguila',
        email: '',
        picture: 'amaury.jpg',
        title: 'CX Developer',
        bio: 'Amaury Aguila is a computer systems engineer with an expertise in machine learning and data science. He holds a master’s degree in Computer Science, and is currently pursuing a doctoral degree in computer science.',
      },
      {
        name: 'Evan Lin',
        email: '',
        picture: 'evan.jpg',
        title: 'BBS and Kitty Cash developer',
        bio: 'Evan Lin is Skycoin’s main developer for Skycoin BBS. Lin left university to pursue a career in software development. His personal projects include; cross-platform applications written using the Qt framework with QML/ C++; APIs in Golang and Node.JS hosted on cloud services such as AWS and GCS; creation of an ROS package for maintaining linear movement via rotary encoders for dual-wheeled robots. Lin is passionate about open- source technology, cryptocurrency, decentralized applications, and linux.',
      },
      {
        name: 'Konstantin Ivanov',
        email: '',
        picture: 'konstantin.jpg',
        title: 'CXO Developer',
        bio: '',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Mike Doty',
        title: 'Co-Founder of Ark',
        picture: 'mike.jpg',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: 'michael.jpg',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners',
        picture: 'richard.jpg',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: 'john.jpg',
        bio: 'John Henry Clippinger is currently a research scientist at the MIT Media Lab’s Human Dynamics Group. He is also Co-Founder and Executive Director of ID3. Previously, Dr. Clippinger was Founder and Co-director of The Law Lab at Harvard University. He is also a member of the eG8 Forum and the Global Leadership Telco Council and the Risk Analysis Network for the World Economic Forum.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: 'patrick.jpg',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: 'josh.jpg',
        bio: 'Founder of three successful online marketing and advertising companies, Ogle grew each business from less than $50k in funding to six-figure profits profits within two years. Ogle specializes in lead generation and free or cheap ways to grow business, including unusual approaches to making products/services “go viral.” He is a Cornell University alumnus.',
      },
      {
        name: 'Andrew Masanto',
        title: 'Board Of Directors at Cornerstone Capital Inc. | Entrepreneur and Investor',
        picture: 'andrew.jpg',
        bio: 'Andrew Masanto currently runs a US investment Holding Company, Land Invest LLC, and is an active advisor to several specialty media buying companies. Previously, he founded www.altitudeshoes.com which became the UK’s leading seller of Men’s Height Increasing Shoes. After its sale, Masanto founded Higher Click SEO Agency (acquired in 2013). He has also lectured at Harvard Business School and Oxford University on the topic of digital marketing.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: 'alphabit.jpg',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: 'tokenkey.jpg',
        bio: 'TokenKey is an end-to-end solution for ICO and token launches.',
      },
    ],
  },
};
