export const en = {
  title: 'Meat the Team',
  subtitle: 'Lorem Ipsum is simply dummy text of the printing',
  quote: 'It takes extraordinary people to do extraordinary things. The Skycoin team is an assembly of the best and brightest to create the future.',
  description: 'Bios of the Skycoin team',
  readBio: 'Read BIO',
  hide: 'Hide',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Brandon Smietana',
        email: '',
        picture: '',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he developed several popular enterprise eCommerce backends. His background includes software development, mathematics, and chemistry.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin Team',
    bios: [
      {
        name: 'Sam Sing Fong',
        email: '',
        picture: '',
        title: 'Operations Lead',
        bio: 'In 2017, Sam began strategic development of Skycoin’s China team. Sam is a co-founder of a blockchain foundation and a founding partner of bluePro Consulting—a management consulting firm with offices in Shanghai and Singapor Sam has also held senior roles in a variety of Fortune 500 companies. Sam is an alumnus of the University of South Australia.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: '',
        title: 'Eastern Operations',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: '',
        title: 'Engineering Leadership',
        bio: 'Simon has 28 years experience delivering secure, high-availability, high-volume platforms. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Jonathan Wilson',
        email: 'jonathan@skycoin.net',
        picture: '',
        title: 'Branding and Communications',
        bio: 'Jonathan is an experienced crypto trader, investor and strategist. He holds degrees in Marketing and International Business from Southeastern University, he is a researcher and consultant in crypto.',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: '',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Mike Doty',
        title: 'Co-Founder of ARK | Co-Founder of Bitseed',
        picture: '',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017). Director of Cryptoassets Design Group Partner at Blockchain Partners',
        picture: '',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: '',
        bio: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: '',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: '',
        bio: 'Josh has a proven track record of bootstrapping and scaling up companies to powerhouses that help redefine their respective niches. From lead generation to agency work, under his watch each venture has flourished. He brings a savvy understanding of how to operate and scale businesses in a cohesive and productive way to maximize their potential. A Cornell University Alumnus, Josh is passionate about the future of technology and blockchain.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: '',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is a $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: '',
        bio: 'Founded by Chris Emms –Tokenkey is a specialized global team that provides assistance with blockchain projects, ranging from initial idea to delivery, allowing teams to remain project focused. Their services cover assisting projects to procure : whitepapers and business plans, token economics, auditing and rating, structuring and compliance, corporate entity and legal, digital asset creation, advisory board, token issuance and exchange listing, custodial and escrow, marketing and PR, community management and bounty, and cryptocurrency trading and arbitrage.',
      },
      {
        name: 'SharkCIA',
        title: 'Marketing and Strategy',
        picture: '',
        bio: 'SharkCIA is a cryptocurrency intelligence agency specializing in the research, investing, and marketing of blockchain-based companies. With members from around the world, SharkCIA’s experienced team provides growth-hacking, public relations, grassroots community outreach, strategic advisement roles and has helped to propel relatively obscure projects towards wider recognition and increased market capitalization.',
      },
      {
        name: 'Hive Chain Labs',
        title: '',
        picture: '',
        bio: 'Hive Chain Labs alongside HChain capital originates from Silicon valley and focuses on the researching and incubation of interdisciplinary blockchain base projects. HChain are believer of blockchain technology and have a vision to “Make BLockchain Everywhere”. Their investment cases include ICO.com, TKN.com, Scry, RChain, Polkadot amongst others.',
      },
    ],
  },
};

export const zh = {
  title: 'Meat the Team',
  subtitle: 'Lorem Ipsum is simply dummy text of the printing',
  quote: 'It takes extraordinary people to do extraordinary things. The Skycoin team is an assembly of the best and brightest to create the future.',
  description: 'Bios of the Skycoin team',
  readBio: 'Read BIO',
  hide: 'Hide',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Brandon Smietana',
        email: '',
        picture: '',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he developed several popular enterprise eCommerce backends. His background includes software development, mathematics, and chemistry.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin Team',
    bios: [
      {
        name: 'Sam Sing Fong',
        email: '',
        picture: '',
        title: 'Operations Lead',
        bio: 'In 2017, Sam began strategic development of Skycoin’s China team. Sam is a co-founder of a blockchain foundation and a founding partner of bluePro Consulting—a management consulting firm with offices in Shanghai and Singapor Sam has also held senior roles in a variety of Fortune 500 companies. Sam is an alumnus of the University of South Australia.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: '',
        title: 'Eastern Operations',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: '',
        title: 'Engineering Leadership',
        bio: 'Simon has 28 years experience delivering secure, high-availability, high-volume platforms. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Jonathan Wilson',
        email: 'jonathan@skycoin.net',
        picture: '',
        title: 'Branding and Communications',
        bio: 'Jonathan is an experienced crypto trader, investor and strategist. He holds degrees in Marketing and International Business from Southeastern University, he is a researcher and consultant in crypto.',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: '',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Mike Doty',
        title: 'Co-Founder of ARK | Co-Founder of Bitseed',
        picture: '',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017). Director of Cryptoassets Design Group Partner at Blockchain Partners',
        picture: '',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: '',
        bio: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: '',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: '',
        bio: 'Josh has a proven track record of bootstrapping and scaling up companies to powerhouses that help redefine their respective niches. From lead generation to agency work, under his watch each venture has flourished. He brings a savvy understanding of how to operate and scale businesses in a cohesive and productive way to maximize their potential. A Cornell University Alumnus, Josh is passionate about the future of technology and blockchain.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: '',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is a $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: '',
        bio: 'Founded by Chris Emms –Tokenkey is a specialized global team that provides assistance with blockchain projects, ranging from initial idea to delivery, allowing teams to remain project focused. Their services cover assisting projects to procure : whitepapers and business plans, token economics, auditing and rating, structuring and compliance, corporate entity and legal, digital asset creation, advisory board, token issuance and exchange listing, custodial and escrow, marketing and PR, community management and bounty, and cryptocurrency trading and arbitrage.',
      },
      {
        name: 'SharkCIA',
        title: 'Marketing and Strategy',
        picture: '',
        bio: 'SharkCIA is a cryptocurrency intelligence agency specializing in the research, investing, and marketing of blockchain-based companies. With members from around the world, SharkCIA’s experienced team provides growth-hacking, public relations, grassroots community outreach, strategic advisement roles and has helped to propel relatively obscure projects towards wider recognition and increased market capitalization.',
      },
      {
        name: 'Hive Chain Labs',
        title: '',
        picture: '',
        bio: 'Hive Chain Labs alongside HChain capital originates from Silicon valley and focuses on the researching and incubation of interdisciplinary blockchain base projects. HChain are believer of blockchain technology and have a vision to “Make BLockchain Everywhere”. Their investment cases include ICO.com, TKN.com, Scry, RChain, Polkadot amongst others.',
      },
    ],
  },
};

export const ru = {
  title: 'Meat the Team',
  subtitle: 'Lorem Ipsum is simply dummy text of the printing',
  quote: 'It takes extraordinary people to do extraordinary things. The Skycoin team is an assembly of the best and brightest to create the future.',
  description: 'Bios of the Skycoin team',
  readBio: 'Read BIO',
  hide: 'Hide',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Brandon Smietana',
        email: '',
        picture: '',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he developed several popular enterprise eCommerce backends. His background includes software development, mathematics, and chemistry.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin Team',
    bios: [
      {
        name: 'Sam Sing Fong',
        email: '',
        picture: '',
        title: 'Operations Lead',
        bio: 'In 2017, Sam began strategic development of Skycoin’s China team. Sam is a co-founder of a blockchain foundation and a founding partner of bluePro Consulting—a management consulting firm with offices in Shanghai and Singapor Sam has also held senior roles in a variety of Fortune 500 companies. Sam is an alumnus of the University of South Australia.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: '',
        title: 'Eastern Operations',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: '',
        title: 'Engineering Leadership',
        bio: 'Simon has 28 years experience delivering secure, high-availability, high-volume platforms. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Jonathan Wilson',
        email: 'jonathan@skycoin.net',
        picture: '',
        title: 'Branding and Communications',
        bio: 'Jonathan is an experienced crypto trader, investor and strategist. He holds degrees in Marketing and International Business from Southeastern University, he is a researcher and consultant in crypto.',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: '',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Mike Doty',
        title: 'Co-Founder of ARK | Co-Founder of Bitseed',
        picture: '',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017). Director of Cryptoassets Design Group Partner at Blockchain Partners',
        picture: '',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: '',
        bio: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: '',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: '',
        bio: 'Josh has a proven track record of bootstrapping and scaling up companies to powerhouses that help redefine their respective niches. From lead generation to agency work, under his watch each venture has flourished. He brings a savvy understanding of how to operate and scale businesses in a cohesive and productive way to maximize their potential. A Cornell University Alumnus, Josh is passionate about the future of technology and blockchain.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: '',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is a $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: '',
        bio: 'Founded by Chris Emms –Tokenkey is a specialized global team that provides assistance with blockchain projects, ranging from initial idea to delivery, allowing teams to remain project focused. Their services cover assisting projects to procure : whitepapers and business plans, token economics, auditing and rating, structuring and compliance, corporate entity and legal, digital asset creation, advisory board, token issuance and exchange listing, custodial and escrow, marketing and PR, community management and bounty, and cryptocurrency trading and arbitrage.',
      },
      {
        name: 'SharkCIA',
        title: 'Marketing and Strategy',
        picture: '',
        bio: 'SharkCIA is a cryptocurrency intelligence agency specializing in the research, investing, and marketing of blockchain-based companies. With members from around the world, SharkCIA’s experienced team provides growth-hacking, public relations, grassroots community outreach, strategic advisement roles and has helped to propel relatively obscure projects towards wider recognition and increased market capitalization.',
      },
      {
        name: 'Hive Chain Labs',
        title: '',
        picture: '',
        bio: 'Hive Chain Labs alongside HChain capital originates from Silicon valley and focuses on the researching and incubation of interdisciplinary blockchain base projects. HChain are believer of blockchain technology and have a vision to “Make BLockchain Everywhere”. Their investment cases include ICO.com, TKN.com, Scry, RChain, Polkadot amongst others.',
      },
    ],
  },
};

export const ko = {
  title: 'Meat the Team',
  subtitle: 'Lorem Ipsum is simply dummy text of the printing',
  quote: 'It takes extraordinary people to do extraordinary things. The Skycoin team is an assembly of the best and brightest to create the future.',
  description: 'Bios of the Skycoin team',
  readBio: 'Read BIO',
  hide: 'Hide',
  heading: '',
  anonymous: {
    heading: 'Why Anonymous?',
    paragraph: 'You may have noticed that some members of Skycoin share their full name and others do not. At Skycoin, we believe in every individual’s right to privacy on the internet. And we walk the walk for both our users and our team. While professional vetting happens on the internal level, no team member is required to give up personal information publicly that they don’t wish to share.',
  },
  founders: {
    title: 'Founders',
    bios: [
      {
        name: 'Brandon Smietana',
        email: '',
        picture: '',
        title: '',
        bio: 'Synth, one of the earliest developers behind Bitcoin, started Skycoin 8 years ago with a vision of creating a new, decentralized Internet. He sits on the advisory boards of several cryptocurrency projects. Synth has a background in mathematics, distributed systems, and symbolic logic.',
      },
      {
        name: 'Houwu Chen',
        email: '',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he developed several popular enterprise eCommerce backends. His background includes software development, mathematics, and chemistry.',
      },
      {
        name: 'Steve Leonard',
        email: 'tokenc@skycoin.net',
        picture: '',
        title: '',
        bio: 'Steve wrote most of the original Skycoin software. Prior to Skycoin, he created several popular enterprise eCommerce backends. His background includes functional programming, chemistry, and mathematics.',
      },
    ],
  },
  west: {
    title: 'Skycoin Team',
    bios: [
      {
        name: 'Sam Sing Fong',
        email: '',
        picture: '',
        title: 'Operations Lead',
        bio: 'In 2017, Sam began strategic development of Skycoin’s China team. Sam is a co-founder of a blockchain foundation and a founding partner of bluePro Consulting—a management consulting firm with offices in Shanghai and Singapor Sam has also held senior roles in a variety of Fortune 500 companies. Sam is an alumnus of the University of South Australia.',
      },
      {
        name: 'Jesse Sun',
        email: '',
        picture: '',
        title: 'Eastern Operations',
        bio: 'Jesse Sun is both the Founder and head of a fund investing in blockchain startups, applications and cryptocurrencies, as well as bitcoin mining. Before joining the crypto world, he was a management consultant. Sun holds an MBA from the Manchester Business School and a master’s degree from Tongji University.',
      },
      {
        name: 'Simon Hobbs',
        email: '',
        picture: '',
        title: 'Engineering Leadership',
        bio: 'Simon has 28 years experience delivering secure, high-availability, high-volume platforms. He began his career as an engineer on missile guidance software, and later moved into financial services, leading IT projects for Barclays Home Finance Mortgage, Swiss Bank and Cedel Bank. Simon holds a BSc in computer science from the University of Hertfordshire.',
      },
      {
        name: 'Jonathan Wilson',
        email: 'jonathan@skycoin.net',
        picture: '',
        title: 'Branding and Communications',
        bio: 'Jonathan is an experienced crypto trader, investor and strategist. He holds degrees in Marketing and International Business from Southeastern University, he is a researcher and consultant in crypto.',
      },
    ],
  },
  investors: {
    title: 'Key Investors and Advisors',
    bios: [
      {
        name: 'Michael Terpin',
        title: 'Founder and CEO of CoinAgenda',
        picture: '',
        bio: 'Michael Terpin is the Founder and CEO of Transform Group and the Founder of Marketwired. In early 2013, Terpin co-founded BitAngels, which gave birth to the CoinAgenda conference series. He also co-founded early blockchain incubator bCommerce Labs and the Dapps Fund. Currently, Terpin heads the ICO investment committee for the Alphabit Fund and advises numerous blockchain companies and foundations. Terpin has led the PR efforts for more than 150 blockchain companies and foundations.',
      },
      {
        name: 'Mike Doty',
        title: 'Co-Founder of ARK | Co-Founder of Bitseed',
        picture: '',
        bio: 'Mike Doty has over 25 years of experience in mechanical engineering and design, including manufacturing, design, analysis, testing, and systems integration. Doty holds a BS Degree in Engineering and Applied Science from the California Institute of Technology. He is a Certified Quality Engineer (CQE) and Certified Reliability Engineer (CRE).',
      },
      {
        name: 'Richard Kastelein',
        title: 'Founder of the Blockchain News (acquired in 2017). Director of Cryptoassets Design Group Partner at Blockchain Partners',
        picture: '',
        bio: 'Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Dr. John Henry Clippinger',
        title: 'Chief Innovation Officer | Founder of Swytch.io | Founder of Tokencommons.org | Scientist at the MIT Media Lab',
        picture: '',
        bio: 'Founder of the Blockchain News (acquired in 2017) | Director of Cryptoassets Design Group | Partner at Blockchain Partners Richard Kastelein is an award-winning publisher, innovation executive, and entrepreneur. He sits on the advisory boards of half a dozen Blockchain startups. Kastelein has written over 1200 articles on Blockchain technology and startups at Blockchain News, and is published in reputable publications including Harvard Business Review, Wired, and Venturebeat.',
      },
      {
        name: 'Patrick Dai',
        title: 'Founder and CEO of Qtum',
        picture: '',
        bio: 'Dai graduated from Draper University and departed from the Chinese Academy of Sciences before completing the doctoral program. Patrick formerly worked at Alibaba. He has expertise in blockchain technology development and remains committed to its advancement.',
      },
      {
        name: 'Josh Ogle',
        title: 'CEO of Samples.com and The Original Agency | Angel Investor',
        picture: '',
        bio: 'Josh has a proven track record of bootstrapping and scaling up companies to powerhouses that help redefine their respective niches. From lead generation to agency work, under his watch each venture has flourished. He brings a savvy understanding of how to operate and scale businesses in a cohesive and productive way to maximize their potential. A Cornell University Alumnus, Josh is passionate about the future of technology and blockchain.',
      },
      {
        name: 'Alphabit',
        title: 'Digital Currency Fund',
        picture: '',
        bio: 'Co-founded by Liam Robertson, a former currency trader at hedge fund Light Peak Capital in London, Alphabit is a $300 million fund that operates as a cross between an open-ended mutual fund and a hedge fund. Alphabit’s previous investments include Videocoin and Stormx.',
      },
      {
        name: 'TokenKey',
        title: '',
        picture: '',
        bio: 'Founded by Chris Emms –Tokenkey is a specialized global team that provides assistance with blockchain projects, ranging from initial idea to delivery, allowing teams to remain project focused. Their services cover assisting projects to procure : whitepapers and business plans, token economics, auditing and rating, structuring and compliance, corporate entity and legal, digital asset creation, advisory board, token issuance and exchange listing, custodial and escrow, marketing and PR, community management and bounty, and cryptocurrency trading and arbitrage.',
      },
      {
        name: 'SharkCIA',
        title: 'Marketing and Strategy',
        picture: '',
        bio: 'SharkCIA is a cryptocurrency intelligence agency specializing in the research, investing, and marketing of blockchain-based companies. With members from around the world, SharkCIA’s experienced team provides growth-hacking, public relations, grassroots community outreach, strategic advisement roles and has helped to propel relatively obscure projects towards wider recognition and increased market capitalization.',
      },
      {
        name: 'Hive Chain Labs',
        title: '',
        picture: '',
        bio: 'Hive Chain Labs alongside HChain capital originates from Silicon valley and focuses on the researching and incubation of interdisciplinary blockchain base projects. HChain are believer of blockchain technology and have a vision to “Make BLockchain Everywhere”. Their investment cases include ICO.com, TKN.com, Scry, RChain, Polkadot amongst others.',
      },
    ],
  },
};
